Home page basic structure, fetchClient optional params added to make it reusable, header fixed due to request
Hexa-Coders-aug23/product_catalog pull request #24
Opened 2023-12-15 22:52 UTC by BetterSol

2023-12-16 07:04 UTC, sviatikkondur requested changes
Ти чомусь видалила 16000 рядків,що це і чи воно нічого не зламає, бо бібліотеки ти ніякі тут не пушила ще?
![image](https://github.com/Hexa-Coders-aug23/product_catalog/assets/107207978/5140be34-1dbd-4cad-9e59-f10789759dc8)
 Папки для секцій - Brand New i Hot Prices не потрібні, у нас буде slider, який можна кастомізувати.
 
Також slider, видали цю папку з shared/components, ним займається Діма. Краще щоб ти скопіювала свій код з Home Page, Banner Section i Categories section, тим чим ти займаєшся, створила нову бранчу і там вже працювала, бо я не знаю, як пофіксити package-lock.json, А цей PR закрити.

2023-12-16 09:21 UTC, BetterSol commented
1.Це лінтер автоматично правив файл packaje-lock.json, можу просто забрати цей файл. 
2.У нас дуже багато в файлах висвітлюється через лінтер, треба буде щоб хтось одним комітом це поправив.
3.Папки Brand New i Hot Prices я ставила як заглушки, тимчасово, як буде Slider я їх видалю.
4.Папку Slider  зробила для себе, там має бути компонента Slider/Swiper/Autoplay, можу її запхати просто в HomePage.
5.Щодо файлу .api Олени - ок, я розумію, але щоб не дублювати код вирішила перевикористати наявний. @Helen-arch, тобі воно нічого не поламає?

P.S. That's what pull requests are made for ;)

2023-12-16 09:28 UTC, sviatikkondur commented
> 1.Це лінтер автоматично правив файл packaje-lock.json, можу просто забрати цей файл. 2.У нас дуже багато в файлах висвітлюється через лінтер, треба буде щоб хтось одним комітом це поправив. 3.Папки Brand New i Hot Prices я ставила як заглушки, тимчасово, як буде Slider я їх видалю. 4.Папку Slider зробила для себе, там має бути компонента Slider/Swiper/Autoplay, можу її запхати просто в HomePage. 5.Щодо файлу .api Олени - ок, я розумію, але щоб не дублювати код вирішила перевикористати наявний. @Helen-arch, тобі воно нічого не поламає?
> 
> P.S. That's what pull requests are made for ;)

To fix all files changing 
```git config core.autocrlf false```
```git rm --cached -r . ```
```git reset --hard```

Так, прибери package-lock-json з PR,
4. Так перенеси цей компонент в Home Page, так як він юзається тільки там

2023-12-16 18:40 UTC, BetterSol commented
Removed package-lock.json from commit. 
Fixed `Favourites` and `Cart` buttons in BurgerMenu.
Removed unnecessary components from HomePage and used some plugs instead.
Moved my `Slider` folder to `HomePage/components` folder (it's technically Swiper folder).
Waiting for a response from @Helen-arch, if I could make minor changes and use the `getPhones` to get the amount of phones.

2023-12-16 18:55 UTC, sviatikkondur requested changes
Great job! Just don't use phones endpoint to get phones count!
Cool images for banner! You can continue work in this branch!

2023-12-16 18:55 UTC, sviatikkondur commented on src/api/phones.ts
Use https://product-catalog-api-hy23.onrender.com/phones/length to get phones count, it returns only number of phones, without unnecessary information, we have the same for tablets and accessories:

phones - https://product-catalog-api-hy23.onrender.com/phones/length
tablets - https://product-catalog-api-hy23.onrender.com/tablets/length
accessories - https://product-catalog-api-hy23.onrender.com/accessories/length

Remove this file from commit also, we will use these phones only for phones on Phones page

2023-12-18 09:05 UTC, sviatikkondur approved these changes
Great job!

2023-12-18 09:23 UTC, Helen-arch approved these changes
Nice job, I'm approving it!

2023-12-18 09:50 UTC, merged